name: Silent Hill 3 (USA)
sha1: dbb94538294b21be38035c0ce6b78354bdfdf2a7
options:
  basename: SLUS_206.22
  target_path: rom/SLUS_206.22
  elf_path: SLUS_206.22
  find_file_boundaries: True
  asm_path: asm
  rodata_string_guesser_level: 0
  symbol_addrs_path: 
    - symbol_addrs.txt
    - shim_addrs.txt
  reloc_addrs_path: reloc_addrs.txt
  gp_value: 0x3d09f0
  ld_script_path: linkers/SLUS_206.22.ld
  undefined_funcs_auto_path: linkers/sh3_undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/sh3_undefined_syms_auto.main.txt
  asm_nonmatching_label_macro: ""
  migrate_rodata_to_functions: True
  pair_rodata_to_text: True
  section_order: [".text", ".vutext", ".data", ".rodata", ".lit4", ".sdata", ".bss"]
  symbol_name_format: $VRAM
segments:
  - [0x0]
  - name: engine
    type: code
    start: 0x580
    vram: 0x00100000
    bss_size: 0x1BA4B00
    subsegments:
      - [0x000580, asm,     crt0]
      - [0x000760, asm,     text_0]
      - { start: 0x0022c8, type: asm, name: sce,  ld_align_segment_start: 0x8  }
      - [0x0220b0, asm,     sdk/libdbc]
      - [0x022b10, asm,     sdk/libgcc]
      - [0x02bfe8, asm,     unk]
      - { start: 0x02cff0, type: c,   name: main, ld_align_segment_start: 0x10 }
      - [0x02d2a0, asm,     text_1]
      - [0x02f3e0, c,       Chacter/m3_sc]
      - [0x030140, asm,     text_2]
      - [0x03baa0, c,       DS_Pad/ds_sequencer]
      - [0x03d290, asm,     text_3]
      - [0x040950, c,       Chacter_Draw/clani]
      - [0x0410c0, asm,     text_4]
      - [0x041640, c,       Effect2/hh_class_manager]
      - [0x042750, asm,     text_5]
      - [0x043460, c,       Chacter/m3_bgobj]
      - [0x043680, asm,     text_6]
      - [0x057150, c,       Font/dic]
      - [0x0582b0, c,       Font/font]
      - [0x05e0f0, asm,     text_7]
      - [0x0aa690, asm,     GFW/sh3gfw_viewclip]
      - [0x0ab250, asm,     text_8]
      - [0x0b71a0, asm,     view/vc_calc]
      - [0x0b7750, asm,     text_9]
      - [0x0c2130, c,       Heap/utilheap]
      - [0x0c2360, asm,     text_A]
      - [0x0d33f0, c,       Chacter_Draw/model3_n]
      - [0x0d3d00, asm,     text_B]
      - [0x0d42d0, c,       Chacter_Draw/model3_vu0_n]
      - [0x0d6df0, c,       Chacter_Draw/model3_vu1_n]
      - [0x0d90b0, asm,     text_C]
      - [0x0dc100, c,       DBG/dbfntprint]
      - [0x0dc410, asm,     text_D]
      - [0x0dc4d0, asm,     sdk/kernel]
      - [0x0dc970, asm,     text_E]
      - [0x0fdfa0, asm,     cri/cri_0] 
      - [0x10eff0, asm,     text_1_0]
      - [0x110b40, asm,     Effect2/hh_class_0]
      - [0x111420, asm,     Effect2/hh_class_1]
      - [0x111c10, asm,     Effect2/hh_class_2]
      - [0x112100, asm,     Effect2/hh_class_3]
      - [0x1128f0, asm,     Effect2/hh_class_4]
      - [0x1133a0, asm,     Effect2/hh_class_5]
      - [0x113cc0, asm,     text_1_1]
      - [0x116520, asm,     Enemy/en_one]        # DOUBLE_HEAD
      - [0x117180, asm,     text_2_0]
      - [0x1261a0, asm,     Enemy/en_smb]        # SPLIT_WORM
      - [0x12ef30, asm,     text_2_C]
      - [0x12f0f0, c,       Enemy/en_common]
      - [0x130590, asm,     Enemy/en_aid]        # CLOSER
      - [0x131040, asm,     text_2_1]
      - [0x141b20, asm,     Effect2/hh_class_6]
      - [0x142490, asm,     Effect2/hh_class_7]
      - [0x142d90, asm,     Effect2/hh_class_8]
      - [0x143870, asm,     text_1_3]
      - [0x143a40, asm,     Enemy/en_ckn]        # NUMB_BODY
      - [0x144620, asm,     text_2_2]
      - [0x15dcd0, asm,     Enemy/en_nse]        # NURSE
      - [0x15e760, asm,     text_2_3]
      - [0x166ad0, asm,     Enemy/en_deb]        # INSANE_CANCER
      - [0x167530, asm,     text_2_4]
      - [0x187340, asm,     Enemy/en_apb]        # MISSIONARY
      - [0x1876c0, asm,     text_2_D]
      - [0x191480, asm,     Enemy/en_fly]        # PENDULUM
      - [0x19b1f0, asm,     text_2_5]
      - [0x1b7fb0, c,       movie/pss_vibuf]
      - [0x1b8f50, c,       movie/pss_videodec]
      - [0x1b99a0, c,       movie/pss_vobuf]
      - [0x1b9c20, asm,     text_1_4]
      - [0x1ba6a0, asm,     Enemy/en_ap2]        # SCRAPER
      - [0x1bab20, asm,     text_2_6]
      - [0x1d2630, asm,     Enemy/en_shb]        # GOD
      - [0x1d2a40, asm,     text_2_E]
      - [0x1d75a0, asm,     Enemy/en_rod]        # SEWER_MONSTER
      - [0x1d7610, asm,     text_2_7]
      - [0x1e01c0, asm,     Enemy/en_mry]        # CAROUSEL_HORSE
      - [0x1e0360, asm,     text_2_9]
      - [0x1e0c80, asm,     Enemy/en_bhr]        # MEMORY_OF_ALESSA
      - [0x1e1490, asm,     text_2_F]
      - [0x1eea70, asm,     Enemy/en_ded1]       # EN_DED1
      - [0x1eea80, asm,     text_2_8]
      - [0x1f3330, asm,     Effect2/hh_class_9]
      - [0x1f3d50, asm,     Effect2/hh_class_A]
      - [0x1f4a10, asm,     text_1_5]
      - [0x2048e0, asm,     Enemy/en_lie]        # SLURPER_E
      - [0x2052c0, asm,     text_2_A]     
      - [0x20e0d0, c,       Enemy/en_lix]        # SLURPER_X
      - [0x210790, asm,     text_2_B]
      - [0x238080, textbin, vutext]
      - [0x23aa80, data,    data]
      - [0x24f4c0, rodata,  rodata_0]
      - [0x29e180, .rodata, movie/pss_vibuf]
      - [0x29e198, rodata,  movie_pss_videodec]
      - [0x29e1a0, rodata,  rodata_1]
      - [0x2be000, .rodata, DS_Pad/ds_sequencer]
      - [0x2be020, rodata,  rodata_2]
      - [0x2be940, .rodata, Font/font]
      - [0x2be970, rodata,  rodata_3]
      - [0x2c5080, .rodata, Enemy/en_common]
      - [0x2c5110, rodata,  rodata_4]
      - [0x2c8790, .rodata, Enemy/en_lix]
      - [0x2c8910, rodata,  rodata_5]
      - [0x2c8f80, lit4,    lit4]
      - [0x2c8fb0, sdata,   sdata]
      - {vram: 0x3C8B00,   type: bss,  name: bss}
      - {vram: 0x1D0EFB0,  type: .bss, name: Font/font}
      - {vram: 0x1D30570,  type: bss,  name: bss_rest}
  - [0x2C9080]
